// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rotpaobmsllrakdqqnrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvdHBhb2Jtc2xscmFrZHFxbnJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NjAwNTUsImV4cCI6MjA2NjQzNjA1NX0.gKOdpJziHeAh_IbZMTOibjji8jEXL4cQ0bq_-wR0HB8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);